kinematics:
  shoulder:
    x: 0
    y: 0
    z: 0.16266408344911912
    roll: -0
    pitch: 0
    yaw: -4.3300426411096993e-08
  upper_arm:
    x: 4.6595557820510537e-05
    y: 0
    z: 0
    roll: 1.5696521704567779
    pitch: 0
    yaw: 5.2794352243486088e-06
  forearm:
    x: -0.42511371633237954
    y: 0
    z: 0
    roll: 3.1392499957032336
    pitch: 3.1409927187581901
    yaw: -3.1415827007108024
  wrist_1:
    x: -0.39257743706112525
    y: -0.00091674446438964126
    z: 0.13336120244240013
    roll: 0.0068740383866908008
    pitch: -0.0015270291686855688
    yaw: 3.128767111234766e-06
  wrist_2:
    x: 8.0157011691419749e-05
    y: -0.099808552840090284
    z: 1.9340634490279304e-05
    roll: 1.5706025494712319
    pitch: 0
    yaw: 6.5964508534372541e-07
  wrist_3:
    x: -7.0794521393877427e-07
    y: 0.099502143511970925
    z: 8.6736203699017714e-05
    roll: 1.5716680284353677
    pitch: 3.1415926535897931
    yaw: 3.1415926150336961
  hash: calib_2084435398446111785