kinematics:
  shoulder:
    x: 0
    y: 0
    z: 0.16240253450944761
    roll: -0
    pitch: 0
    yaw: -9.0562789260514344e-09
  upper_arm:
    x: 0.00010175893899512032
    y: 0
    z: 0
    roll: 1.5693122172022154
    pitch: 0
    yaw: 2.6956057779477102e-06
  forearm:
    x: -0.42506134357080128
    y: 0
    z: 0
    roll: 3.1413933753942778
    pitch: 3.1388666293721648
    yaw: 3.1415865414224302
  wrist_1:
    x: -0.39224168335951543
    y: -0.00045618563038464505
    z: 0.13412362546244527
    roll: 0.0034012193579919065
    pitch: -0.00056376984653294323
    yaw: 7.2050334924174928e-06
  wrist_2:
    x: 3.8424520394878133e-05
    y: -0.099719170933881426
    z: 5.4707158752120821e-05
    roll: 1.5702477145997562
    pitch: 0
    yaw: 1.7239298139883064e-07
  wrist_3:
    x: 2.030534855515106e-05
    y: 0.099392843434359099
    z: 0.00011987549420800481
    roll: 1.5720024039322575
    pitch: 3.1415926535897931
    yaw: -3.1415925924655874
  hash: calib_10457944374873648035