kinematics:
  shoulder:
    x: 0
    y: 0
    z: 0.16282198625453251
    roll: -0
    pitch: 0
    yaw: -1.2098335023386086e-07
  upper_arm:
    x: 0.00018214070651470778
    y: 0
    z: 0
    roll: 1.5710666540849185
    pitch: 0
    yaw: 1.7902991633851485e-06
  forearm:
    x: -0.42502288894323353
    y: 0
    z: 0
    roll: 0.0026094293274673765
    pitch: -0.00045034314973694969
    yaw: 9.906417675746787e-06
  wrist_1:
    x: -0.39283829675455367
    y: -0.00056436907952624052
    z: 0.13320049311775037
    roll: 0.0042369640618689051
    pitch: -0.0018785693620712186
    yaw: -3.7205282367539484e-06
  wrist_2:
    x: -9.4257702903436142e-06
    y: -0.099734700836119156
    z: 5.1157465293717392e-05
    roll: 1.5702833913734406
    pitch: 0
    yaw: 3.6672631587033287e-06
  wrist_3:
    x: 3.5321480907012735e-05
    y: 0.099528970758092972
    z: 0.00013225121269524751
    roll: 1.5721250970399048
    pitch: 3.1415926535897931
    yaw: -3.1415926108900765
  hash: calib_13202339666004192988