kinematics:
  shoulder:
    x: 0
    y: 0
    z: 0.16275160990278811
    roll: -0
    pitch: 0
    yaw: -2.5886124833344321e-07
  upper_arm:
    x: 0.00015971874630051029
    y: 0
    z: 0
    roll: 1.5708934160101666
    pitch: 0
    yaw: -7.6074896693256733e-07
  forearm:
    x: -0.42522945792202116
    y: 0
    z: 0
    roll: 0.0015650605292727433
    pitch: -5.3700657355127943e-05
    yaw: 1.0131954704943649e-05
  wrist_1:
    x: -0.39275899615393356
    y: -0.00054242658133137978
    z: 0.13311231740757296
    roll: 0.00407493152811689
    pitch: -0.0024280900089875975
    yaw: 2.763319000662249e-07
  wrist_2:
    x: 5.2866484562284407e-05
    y: -0.099760473794059501
    z: 4.6961707687262517e-05
    roll: 1.5703255821960358
    pitch: 0
    yaw: 1.3788591885222077e-06
  wrist_3:
    x: 3.4625513683448948e-05
    y: 0.099480893998451558
    z: 0.00012396208912118111
    roll: 1.5720424155661024
    pitch: 3.1415926535897931
    yaw: 3.1415920714257544
  hash: calib_15442978373683023777