kinematics:
  shoulder:
    x: 0
    y: 0
    z: 0.16229419442676124
    roll: -0
    pitch: 0
    yaw: -9.1666235463305767e-08
  upper_arm:
    x: 0.00013316468768148696
    y: 0
    z: 0
    roll: 1.5696625485168281
    pitch: 0
    yaw: -2.9726252295247946e-06
  forearm:
    x: -0.42496654255549088
    y: 0
    z: 0
    roll: 0.00012310205010096636
    pitch: 0.0023852947016547335
    yaw: -9.1735908063718954e-07
  wrist_1:
    x: -0.39217905023109906
    y: 0.00046912687574673359
    z: 0.13351854956216089
    roll: 3.1380790972576262
    pitch: -3.1392249793271154
    yaw: 3.1415846943887238
  wrist_2:
    x: -5.9477452574606223e-05
    y: -0.099459805870289242
    z: 9.7798611986313488e-05
    roll: 1.5698130292747485
    pitch: 0
    yaw: 6.1167596019165448e-07
  wrist_3:
    x: 0.00010317889633428283
    y: 0.099439994790583672
    z: 0.00015845582409268146
    roll: 1.5723898072683258
    pitch: 3.1415926535897931
    yaw: 3.1415926269283476
  hash: calib_10921388720633806739